language: python
sudo: false
cache: pip

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install tox-travis

script:
  - tox
  - coverage run --append --source . setup.py build_ext --inplace
  - coverage run --source icon_font_to_png -m py.test
  - coverage report -m

after_success:
  - coveralls
